import { createAction } from '@reduxjs/toolkit';

export enum MessagingEvent {
  CREATE_CONVERSATION = 'CREATE_CONVERSATION',
  JOIN_CONVERSATION = 'JOIN_CONVERSATION',
  UPDATE_CONVERSATION = 'UPDATE_CONVERSATION',
  LEAVE_CONVERSATION = 'LEAVE_CONVERSATION',
  SEND_MESSAGE = 'SEND_MESSAGE',
  UPDATE_MESSAGE = 'UPDATE_MESSAGE',
  REMOVE_MESSAGE = 'REMOVE_MESSAGE',
  CREATE_THREAD = 'CREATE_THREAD',
  JOIN_TEAM = 'JOIN_TEAM',
  CREATE_TEAM = 'CREATE_TEAM',
  LEAVE_TEAM = 'LEAVE_TEAM',
  READ_TEAM = 'READ_TEAM',
  READ_CHANNEL = 'READ_CHANNEL',
  ASSIGN_CHANNEL_ADMIN = 'ASSIGN_CHANNEL_ADMIN',
  ASSIGN_TEAM_ADMIN = 'ASSIGN_TEAM_ADMIN',
  USER_STATUS = 'USER_STATUS',
  ADD_USER = 'ADD_USER',
  REMOVE_USER = 'REMOVE_USER',
  SEND_NOTIFICATION = 'SEND_NOTIFICATION',
  DELETE_CONVERSATION = 'DELETE_CONVERSATION',
  UPDATE_TEAM = 'UPDATE_TEAM',
  FETCH_TEAMS = 'FETCH_TEAMS',
  UNREAD_THREAD = 'UNREAD_THREAD',
  READ_THREAD = 'READ_THREAD',
  REACTION_ADDED = 'REACTION_ADDED',
  REACTION_REMOVED = 'REACTION_REMOVED',
  GLOBAL_SIGN_OUT = 'GLOBAL_SIGN_OUT',
  UPDATE_USER_STATUS = 'UPDATE_USER_STATUS'
}

export type TMessageType = {
  content: string;
  conversationId: number;
};

export const sendMessage = createAction<TMessageType>(
  MessagingEvent.SEND_MESSAGE
);
